# 2 - VARIABLES AND BASIC DATA STRUCTURES

## Summary
1. Storing, retrieving, and manipulating information and data is important in any scientific and engineering field.
2. Assigning variables is an important tool for handling data values.
3. There are different data types for storing information in Python: int, float, and boolean for single values, and strings, lists, tuples, sets, and dictionaries for sequential data.
4. The NumPy array is a powerful data structure that used a lot in scientific computing.

## Problems

### 5. Assign string "123" to the variable S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the type function.

In [2]:
s = "123"
n = float(s)
type(n)

float

### 7. Use the print function to generate the following strings:
• The world "Engineering" has 11 letters.
• The word "Book" has 4 letters.

In [4]:
print(len("Engineering"))
print(len("Book"))

11
4


### 8. Check if "Python" is in "Python is great!".

In [7]:
print("Python" in "Python is great")

True


### 9. Get the last word "great" from "Python is great!"

In [28]:
pg = "Python is great!"
print(pg[-6:])
if ("great" in "Python is great!"):
    print ("great") 
else:
    print ("great is not in the sentence")

great!
great is not in the sentence


### 10. Assign list [1, 8, 9, 15] to a variable list_a and insert 2 at index 1 using the insert method. Append 4 to the list_a using the append method.

In [30]:
list_a = [1, 8, 9, 15]
list_a.insert(1, 2)
list_a.append(4)
print(list_a)

[1, 2, 8, 9, 15, 4]


### 11. Sort the list_a in problem 10 in ascending order.
https://www.w3schools.com/python/ref_list_sort.asp

In [36]:
list_a.sort(reverse=False)
list_a

[1, 2, 4, 8, 9, 15]

### 12. Turn "Python is great!" into a list.

In [37]:
list("Python is great!")

['P',
 'y',
 't',
 'h',
 'o',
 'n',
 ' ',
 'i',
 's',
 ' ',
 'g',
 'r',
 'e',
 'a',
 't',
 '!']

### 13. Create one tuple with element "One", 1 and assign it to tuple_a. 14. Get the second element in the tuple_a

In [39]:
tuple_a = ("one", 1)
tuple_a[1]

1

### 15. Get the unique element from (2, 3, 2, 3, 1, 2, 5).

In [44]:
set((2,3,2,3,1,2,5)) #pake dua kurung

{1, 2, 3, 5}

### 16. Assign (2, 3, 2) to set_a, and (1, 2, 3) to set_b. Obtain the following:
- union of set_a and set_b
- intersection of set_a and set_b
- difference of set_a to set_b using difference method

In [4]:
set_a = set((2, 3, 2))
set_b = set((1, 2, 3))
print(set_a.union(set_b))
print(set_a.intersection(set_b))
print(set_a.difference(set_b))

{1, 2, 3}
{2, 3}
set()


### 17. Create a dictionary that has the keys "A", "B", "C" with values "a", "b", "c" individually. Print all the keys in the dictionary.
### 18. Check if key "B" is in the dictionary defined in Problem 17.

In [7]:
dict = {"A":"a", "B":"b", "C":"c"}
print(dict.keys())

dict_keys(['A', 'B', 'C'])


### 19. Create array x and y, where x = [1, 4, 3, 2, 9, 4] and y=[2, 3, 4, 1, 2, 3]. Compute the assignments from Problem 3.
- u = x + y
- v = xy
- w = x/y
- z = sin(x)
- r = 8sin(x)
- s = 5sin(xy)
- p = x**y

In [16]:
import numpy as np
x = np.array((1,4,3,2,9,4))
y = np.array((2,3,4,1,2,3))
u = x+y
v = x*y
w = x/y
z = np.sin(x)
r = 8*np.sin(x)
s = 5*np.sin(x*y)
p = x**y

### 20. Generate an array with size 100 evenly spaced between −10 to 10 using linspace function in NumPy.

In [17]:
arraynoduapuluh = np.linspace(-10,10,100)
arraynoduapuluh

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

### 21. Let array_a be an array [-1, 0, 1, 2, 0, 3]. Write a command that will return an array consisting of all the elements of array_a that are larger than zero. 
Hint: Use logical expression as the index of the array.

In [30]:
larik = np.array((-1, 0, 1, 2, 0, 3))
larik > 0

array([False, False,  True,  True, False,  True])

In [33]:
larikk = np.array(([3, 5 ,3],
                   [2, 2, 5],
                   [3, 8, 9]))
larikk.transpose()

array([[3, 2, 3],
       [5, 2, 8],
       [3, 5, 9]])

In [40]:
larikzero = np.zeros((2,4))
print(larikzero)
larikzero[:,1] = 1
print(larikzero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [41]:
reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [42]:
%whos

Interactive namespace is empty.
